<?php
/**
 * @file
 *  Provides a generic but powerful API for web services.
 */

/**
 * Implementation of hook_services_resources().
 */
function yunomi_rest_home_services_resources() {
  $resources = array();
  // GET 4 articles, 1 openhartig and 4 recipes for homepage.
  $resources['home'] = array();
  $resources['home']['index'] = array(
    'help' => 'This method gets articles, openhartig and recipes for homepage.',
    'file' => array(
      'type' => 'inc',
      'module' => 'yunomi_rest_home',
      'name' => 'resources/yunomi_rest_home.resource',
    ),
    'callback' => '_yunomi_rest_home',
    'args' => array(
      array(
      'name' => 'page',
      'optional' => TRUE,
      'type' => 'int',
      'description' => 'The zero-based index of the page to get, defaults to 0.',
      'default value' => 0,
      'source' => array('param' => 'page'),
      ),
    ),
    'access arguments' => array('access content'),
  );
  
 return $resources;
}
