<?php
/**
 * @file
 *  Provides a generic but powerful API for web services.
 */


/**
 * Implementation of hook_services_resources().
 */
function yunomi_rest_article_services_resources() {
  $resources = array();
  
  $resources['articles'] = array();
  $resources['articles']['retrieve'] = array(
    'help' => 'This method retrieves a list of recent articles.',
    'file' => array(
      'type' => 'inc',
      'module' => 'yunomi_rest_article',
      'name' => 'resources/yunomi_rest_articles.resource',
    ),
    'callback' => '_yunomi_rest_articles_view',
    'access callback' => '_yunomi_rest_access',
    'access arguments' => array('view'),
    'access arguments append' => TRUE,
    'args' => array(
      'case' => array(
        'name' => 'case',
        'type' => 'string',
        'description' => 'The case of retrieve to get.',
        'source' => array('path' => '0'),
        'optional' => FALSE,
      ),
      array(
          'name' => 'query',
          'optional' => TRUE,
          'type' => 'string',
          'description' => 'Search query.',
          'default value' => NULL,
          'source' => array('param' => 'query'),
      ),  
      'qid' => array(
        'name' => 'qid',
        'type' => 'string',
        'description' => 'The name of the view to get.',
        'source' => array('param' => 'qid'),
        'optional' => TRUE,
      ),  
      'offset' => array(
        'name' => 'offset',
        'type' => 'int',
        'description' => 'The number of the entry for the page begin with.',
        'source' => array('param' => 'offset'),
        'optional' => TRUE,
        'default value' => 0,
      ),
      'limit' => array(
        'name' => 'limit',
        'type' => 'int',
        'description' => 'The total number of entries to list.',
        'source' => array('param' => 'limit'),
        'optional' => TRUE,
        'default value' => 10,
      ),
      'term' => array(
        'name' => 'term',
        'type' => 'string',
        'description' => 'The term argument to be passed to view.',
        'source' => array('param' => 'term'),
        'optional' => TRUE,
      ),  
    ),
  );
  // Get Article node with a specified ID.
  $resources['article'] = array();
  $resources['article']['retrieve'] = array(
    'help' => 'This method retrieves an article by nid.',
    'file' => array('type' => 'inc', 'module' => 'yunomi_rest_article', 'name' => 'resources/yunomi_rest_article.resource'),
    'callback' => '_yunomi_rest_article_retrieve',
    'args' => array(
      array(
        'name' => 'nid',
        'optional' => FALSE,
        'source' => array('path' => 0),
        'type' => 'int',
        'description' => 'The nid of the node to get',
      ),
    ),
    'access callback' => '_yunomi_rest_access',
    'access arguments' => array('view'),
    'access arguments append' => TRUE,
  );
 
  return $resources;
}
