<?php
/**
 * @file
 *  Provides a generic but powerful API for web services.
 */

/**
 * Implementation of hook_services_resources().
 */
function yunomi_rest_recipe_services_resources() {
  $resources = array();
  
  // GET recent recipes resources.
  $resources['recipes'] = array();
  $resources['recipes']['retrieve'] = array(
    'help' => 'This method gets a list of recent recipes.',
    'file' => array(
      'type' => 'inc',
      'module' => 'yunomi_rest_recipe',
      'name' => 'resources/yunomi_rest_recipes.resource',
    ),
    'callback' => '_yunomi_rest_recipes_week',
    'access callback' => '_yunomi_rest_access',
    'access arguments' => array('view'),
    'access arguments append' => TRUE,
    'args' => array(
      'view_name' => array(
        'name' => 'view_name',
        'type' => 'string',
        'description' => 'The name of the view to get.',
        'source' => array('path' => '0'),
        'optional' => FALSE,
      ),
    ),
  );
  // Get Test&Tell node with a specified ID.
  $resources['recipe'] = array();
  $resources['recipe']['retrieve'] = array(
    'help' => 'This method retrieves a certain recipe by ID.',
    'file' => array('type' => 'inc', 'module' => 'yunomi_rest_recipe', 'name' => 'resources/yunomi_rest_recipe.resource'),
    'callback' => '_yunomi_rest_recipe_retrieve',
    'args' => array(
      array(
        'name' => 'arg',
        'optional' => FALSE,
        'source' => array('path' => 0),
        'type' => 'string',
        'description' => 'The nid/option of the recipes to get',
      ),
      array(
        'name' => 'query',
        'optional' => TRUE,
        'type' => 'string',
        'description' => 'Livelink search query.',
        'default value' => NULL,
        'source' => array('param' => 'query'),
      ),
      array(
        'name' => 'moment',
        'optional' => TRUE,
        'type' => 'string',
        'description' => 'The moment of the day.',
        'default value' => NULL,
        'source' => array('param' => 'moment'),
      ), 
      array(
        'name' => 'menu',
        'optional' => TRUE,
        'type' => 'string',
        'description' => 'The menu to search in.',
        'default value' => NULL,
        'source' => array('param' => 'menu'),
      ),  
      array(
        'name' => 'preparation',
        'optional' => TRUE,
        'type' => 'string',
        'description' => 'Preparation time.',
        'default value' => NULL,
        'source' => array('param' => 'preparation'),
      ),  
      array(
        'name' => 'recept',
        'optional' => TRUE,
        'type' => 'string',
        'description' => 'Recept to search in.',
        'default value' => NULL,
        'source' => array('param' => 'recept'),
      ),    
      array(
        'name' => 'gerecht',
        'optional' => TRUE,
        'type' => 'string',
        'description' => 'Recept to search in.',
        'default value' => NULL,
        'source' => array('param' => 'gerecht'),
      ),    
      array(
        'name' => 'keuken',
        'optional' => TRUE,
        'type' => 'string',
        'description' => 'Recept to search in.',
        'default value' => NULL,
        'source' => array('param' => 'keuken'),
      ),      
      array(
        'name' => 'season',
        'optional' => TRUE,
        'type' => 'string',
        'description' => 'Recept to search in.',
        'default value' => NULL,
        'source' => array('param' => 'season'),
      ),      
      array(
        'name' => 'gelegenheid',
        'optional' => TRUE,
        'type' => 'string',
        'description' => 'Recept to search in.',
        'default value' => NULL,
        'source' => array('param' => 'gelegenheid'),
      ),        
      array(
        'name' => 'livelinkID',
        'optional' => TRUE,
        'type' => 'string',
        'description' => 'LiveLink Id of the recipe.',
        'default value' => NULL,
        'source' => array('param' => 'livelinkID'),
      ),  
    ),
    'access callback' => '_yunomi_rest_access',
    'access arguments' => array('view'),
    'access arguments append' => TRUE,
  );
  $resources['recipe']['relationships'] = array(
    'ratings' => array(
      'file' => array('type' => 'inc', 'module' => 'yunomi_rest_recipe', 'name' => 'resources/yunomi_rest_recipe.resource'),
      'help'   => t('This method returns ratings associated with a node.'),
      'access callback' => '_yunomi_rest_access',
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
      'callback' => '_yunomi_rest_recipe_resource_load_ratings',
      'args'     => array(
        array(
          'name' => 'nid',
          'optional' => FALSE,
          'source' => array('path' => 0),
          'type' => 'int',
          'description' => 'The livelink id of the node whose rating we are getting',
        ),
      ),
    ),
  ); 
  $resources['recipe']['targeted_actions'] = array(
    'rating' => array(
      'help' => 'This method post reting for livelink recipe.',
      'file' => array('type' => 'inc', 'module' => 'yunomi_rest_recipe', 'name' => 'resources/yunomi_rest_recipe.resource'),
      'access callback' => '_yunomi_rest_access',
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
      'callback' => '_yunomi_rest_recipe_resource_post_rating',
      'args' => array(
        array(
         'name' => 'rid',
         'optional' => FALSE,
         'source' => array('path' => 0),
         'type' => 'string',
         'description' => 'The livelink id for the rating.',
        ),
        array(
        'name' => 'data',
        'type' => 'array',
        'description' => 'The rating from 1 to 5.',
        'source' => 'data',
        'optional' => FALSE,
        ),
      ),
    ),
    'media' => array(
      'help' => 'This method does request to post a new media for a given node',
      'file' => array('type' => 'inc', 'module' => 'yunomi_rest_recipe', 'name' => 'resources/yunomi_rest_recipe.resource'),
      'access callback' => '_yunomi_rest_access',
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
      'callback' => '_yunomi_rest_recipe_resource_post_media',
      'args' => array(
        array(
         'name' => 'nid',
         'optional' => FALSE,
         'source' => array('path' => 0),
         'type' => 'int',
         'description' => 'The id of the Node for which we post a media.',
        ),
        array(
        'name' => 'data',
        'type' => 'array',
        'description' => 'The media data.',
        'source' => 'data',
        'optional' => FALSE,
        ),
      ),
    ),  
  );
  $resources['recipe']['relationships'] = array(
    'medias' => array(
      'file' => array('type' => 'inc', 'module' => 'yunomi_rest_recipe', 'name' => 'resources/yunomi_rest_recipe.resource'),
      'help'   => t('This method returns medias associated with a node.'),
      'access callback' => '_yunomi_rest_access',
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
      'callback' => '_yunomi_rest_recipe_resource_load_media',
      'args'     => array(
        array(
          'name' => 'nid',
          'optional' => FALSE,
          'source' => array('path' => 0),
          'type' => 'int',
          'description' => 'The nid of the node whose medias we are getting',
        ),
      ),
    ),
  );
  
  return $resources;
}
